export { FETCH_START, FETCH_END, FETCH_ERROR, FETCH_CANCEL } from 'react-admin';

export const FETCH_ERROR_AUTH = 'RA/FETCH_ERROR_AUTH';
export const FETCH_ERROR_VALIDATION = 'RA/FETCH_ERROR_VALIDATION';
export const FETCH_ERROR_HANDLED = 'RA/FETCH_ERROR_HANDLED';
export const FETCH_ERROR_UNHANDLED = 'RA/FETCH_ERROR_UNHANDLED';